dist: trusty
sudo: required
language: php
php:
  - '7.0'
  - '7.1'
  
services:
  - mysql
  - redis-server

before_install:  
  - mysql -e 'CREATE DATABASE IF NOT EXISTS squanch_cache;'
  - mysql -u root --default-character-set=utf8 squanch_cache < db/mysql.sql
  
before_script:
  - composer install --prefer-source --no-interaction --dev
  
script:
  - composer test